using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace LicenseVerifier
{
    /// <summary>
    /// License data model containing all fields from the license file.
    /// </summary>
    public class LicenseInfo
    {
        public string LicenseId { get; set; } = "";
        public string LicenseeName { get; set; } = "";
        public string LicenseeEmail { get; set; } = "";
        public string CompanyName { get; set; } = "";
        public string ProductName { get; set; } = "";
        public string ProductVersion { get; set; } = "";
        public string LicenseType { get; set; } = "";
        public DateTime IssuedDate { get; set; }
        public DateTime ExpiryDate { get; set; }
        public int MaxMachines { get; set; }
        public string Features { get; set; } = "";

        public bool IsExpired => DateTime.Now.Date > ExpiryDate;

        public List<string> FeatureList =>
            string.IsNullOrEmpty(Features)
                ? new List<string>()
                : Features.Split(',').Select(f => f.Trim()).ToList();

        public override string ToString()
        {
            return $"License ID:    {LicenseId}\n" +
                   $"Licensee:      {LicenseeName} ({LicenseeEmail})\n" +
                   $"Company:       {CompanyName}\n" +
                   $"Product:       {ProductName} v{ProductVersion}\n" +
                   $"Type:          {LicenseType}\n" +
                   $"Issued:        {IssuedDate:yyyy-MM-dd}\n" +
                   $"Expires:       {ExpiryDate:yyyy-MM-dd}\n" +
                   $"Max Machines:  {MaxMachines}\n" +
                   $"Features:      {Features}\n" +
                   $"Status:        {(IsExpired ? "EXPIRED" : "ACTIVE")}";
        }
    }

    /// <summary>
    /// Result of a license verification attempt.
    /// </summary>
    public class LicenseValidationResult
    {
        public bool IsValid { get; set; }
        public string ErrorMessage { get; set; } = "";
        public LicenseInfo? License { get; set; }
    }

    /// <summary>
    /// Verifies digitally signed license files generated by the PHP server.
    ///
    /// Usage:
    ///   var validator = new LicenseValidator();
    ///   var result = validator.ValidateLicenseFile("path/to/license.lic");
    ///   if (result.IsValid && !result.License.IsExpired) { /* licensed */ }
    /// </summary>
    public class LicenseValidator
    {
        // =====================================================================
        // EMBEDDED PUBLIC KEY - Generated by generate_keys.php on your server.
        // Replace this with YOUR public key after running generate_keys.php.
        // =====================================================================
        private const string PublicKeyPem = @"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz9PgWfxP80u59mcbIWc6
1XycQGxpj9K7BbNncD0jvyXQ9HzGzZrs9hMAUKfMt5KoMTd1ExB7MmWjrdRp5+60
9xlSL65YYpY8c/RzgGJUxpnFP3FAmMui9Y9zB3PLaHFlOQBzm7z5QpzvweMM8Rt2
0iMrXm6xv3EgVPSQoMq/KpSiJ/FHGrbY5aPhvQfUzZJw3A02B3Jti3HkRbDmMjPT
XNRXY+3vHMyCHj/l2u63oJSOiMW04UUTfzZ1RDopL5Ie9+5xWXLpysUwgQkqZ4nr
tKq1AIcIFIwRJpHJzwqwJZXopUubX4NHt15lKH28o3BtjcTwGlhQoWtyP8g47HtE
jwIDAQAB
-----END PUBLIC KEY-----";

        /// <summary>
        /// Validate a license file from a file path.
        /// </summary>
        public LicenseValidationResult ValidateLicenseFile(string filePath)
        {
            try
            {
                if (!File.Exists(filePath))
                {
                    return new LicenseValidationResult
                    {
                        IsValid = false,
                        ErrorMessage = $"License file not found: {filePath}"
                    };
                }

                string content = File.ReadAllText(filePath);
                return ValidateLicenseContent(content);
            }
            catch (Exception ex)
            {
                return new LicenseValidationResult
                {
                    IsValid = false,
                    ErrorMessage = $"Error reading license file: {ex.Message}"
                };
            }
        }

        /// <summary>
        /// Validate license from raw content string.
        /// </summary>
        public LicenseValidationResult ValidateLicenseContent(string licenseContent)
        {
            try
            {
                // Parse the license file
                var lines = licenseContent.Trim().Split('\n')
                    .Select(l => l.Trim())
                    .Where(l => !string.IsNullOrEmpty(l))
                    .ToArray();

                if (lines.Length < 4 ||
                    lines[0] != "----BEGIN LICENSE----" ||
                    lines[2] != "----BEGIN SIGNATURE----" ||
                    lines[4] != "----END LICENSE----")
                {
                    return new LicenseValidationResult
                    {
                        IsValid = false,
                        ErrorMessage = "Invalid license file format."
                    };
                }

                string dataBase64 = lines[1];
                string signatureBase64 = lines[3];

                // Decode the data and signature
                byte[] dataBytes = Encoding.UTF8.GetBytes(
                    Encoding.UTF8.GetString(Convert.FromBase64String(dataBase64))
                );
                byte[] signatureBytes = Convert.FromBase64String(signatureBase64);

                // Verify the signature using RSA + SHA256
                bool signatureValid = VerifySignature(dataBytes, signatureBytes);

                if (!signatureValid)
                {
                    return new LicenseValidationResult
                    {
                        IsValid = false,
                        ErrorMessage = "License signature verification failed. The license may be tampered with."
                    };
                }

                // Parse the license JSON data
                string jsonString = Encoding.UTF8.GetString(Convert.FromBase64String(dataBase64));
                var licenseInfo = ParseLicenseJson(jsonString);

                return new LicenseValidationResult
                {
                    IsValid = true,
                    License = licenseInfo
                };
            }
            catch (Exception ex)
            {
                return new LicenseValidationResult
                {
                    IsValid = false,
                    ErrorMessage = $"License validation error: {ex.Message}"
                };
            }
        }

        /// <summary>
        /// Verify RSA-SHA256 signature using the embedded public key.
        /// </summary>
        private bool VerifySignature(byte[] data, byte[] signature)
        {
            using var rsa = RSA.Create();
            rsa.ImportFromPem(PublicKeyPem.ToCharArray());

            return rsa.VerifyData(
                data,
                signature,
                HashAlgorithmName.SHA256,
                RSASignaturePadding.Pkcs1
            );
        }

        /// <summary>
        /// Parse the JSON license data into a LicenseInfo object.
        /// </summary>
        private LicenseInfo ParseLicenseJson(string json)
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            return new LicenseInfo
            {
                LicenseId = GetStringOrDefault(root, "license_id"),
                LicenseeName = GetStringOrDefault(root, "licensee_name"),
                LicenseeEmail = GetStringOrDefault(root, "licensee_email"),
                CompanyName = GetStringOrDefault(root, "company_name"),
                ProductName = GetStringOrDefault(root, "product_name"),
                ProductVersion = GetStringOrDefault(root, "product_version"),
                LicenseType = GetStringOrDefault(root, "license_type"),
                IssuedDate = DateTime.Parse(GetStringOrDefault(root, "issued_date", "2000-01-01")),
                ExpiryDate = DateTime.Parse(GetStringOrDefault(root, "expiry_date", "2000-01-01")),
                MaxMachines = GetIntOrDefault(root, "max_machines", 1),
                Features = GetStringOrDefault(root, "features"),
            };
        }

        private static string GetStringOrDefault(JsonElement root, string property, string defaultValue = "")
        {
            return root.TryGetProperty(property, out var el) ? el.GetString() ?? defaultValue : defaultValue;
        }

        private static int GetIntOrDefault(JsonElement root, string property, int defaultValue = 0)
        {
            if (!root.TryGetProperty(property, out var el)) return defaultValue;
            return el.ValueKind == JsonValueKind.Number ? el.GetInt32() : defaultValue;
        }
    }
}
